In [47]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.naive_bayes import CategoricalNB
from sklearn.neural_network import MLPClassifier

In [48]:
df = pd.read_csv('abalone19.csv')

In [49]:
from sklearn.preprocessing import OneHotEncoder
encoder = OneHotEncoder()
d = encoder.fit_transform(df[['Sex']]).toarray()
dd=pd.DataFrame(d,columns=encoder.get_feature_names())
dd
df['Sex_F']=dd['x0_F']
df['Sex_I']=dd['x0_I']
df['Sex_M']=dd['x0_M']
df.drop('Sex',axis=1,inplace=True)
df

,Length,Diameter,Height,Whole_weight,Shucked_weight,Viscera_weight,Shell_weight,Class,Sex_F,Sex_I,Sex_M
0,0.455,0.365,0.095,0.5140,0.2245,0.1010,0.1500,negative,0.0,0.0,1.0
1,0.350,0.265,0.090,0.2255,0.0995,0.0485,0.0700,negative,0.0,0.0,1.0
2,0.530,0.420,0.135,0.6770,0.2565,0.1415,0.2100,negative,1.0,0.0,0.0
3,0.440,0.365,0.125,0.5160,0.2155,0.1140,0.1550,negative,0.0,0.0,1.0
4,0.330,0.255,0.080,0.2050,0.0895,0.0395,0.0550,negative,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...
4169,0.560,0.430,0.155,0.8675,0.4000,0.1720,0.2290,negative,0.0,0.0,1.0
4170,0.565,0.450,0.165,0.8870,0.3700,0.2390,0.2490,negative,1.0,0.0,0.0
4171,0.590,0.440,0.135,0.9660,0.4390,0.2145,0.2605,negative,0.0,0.0,1.0
4172,0.600,0.475,0.205,1.1760,0.5255,0.2875,0.3080,negative,0.0,0.0,1.0
4173,0.625,0.485,0.150,1.0945,0.5310,0.2610,0.2960,negative,1.0,0.0,0.0

In [50]:
x=df.drop("Class",axis=1)
x

,Length,Diameter,Height,Whole_weight,Shucked_weight,Viscera_weight,Shell_weight,Sex_F,Sex_I,Sex_M
0,0.455,0.365,0.095,0.5140,0.2245,0.1010,0.1500,0.0,0.0,1.0
1,0.350,0.265,0.090,0.2255,0.0995,0.0485,0.0700,0.0,0.0,1.0
2,0.530,0.420,0.135,0.6770,0.2565,0.1415,0.2100,1.0,0.0,0.0
3,0.440,0.365,0.125,0.5160,0.2155,0.1140,0.1550,0.0,0.0,1.0
4,0.330,0.255,0.080,0.2050,0.0895,0.0395,0.0550,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...
4169,0.560,0.430,0.155,0.8675,0.4000,0.1720,0.2290,0.0,0.0,1.0
4170,0.565,0.450,0.165,0.8870,0.3700,0.2390,0.2490,1.0,0.0,0.0
4171,0.590,0.440,0.135,0.9660,0.4390,0.2145,0.2605,0.0,0.0,1.0
4172,0.600,0.475,0.205,1.1760,0.5255,0.2875,0.3080,0.0,0.0,1.0
4173,0.625,0.485,0.150,1.0945,0.5310,0.2610,0.2960,1.0,0.0,0.0

In [51]:
y=df["Class"]

In [52]:
y

0       negative
1       negative
2       negative
3       negative
4       negative
          ...
4169    negative
4170    negative
4171    negative
4172    negative
4173    negative
Name: Class, Length: 4174, dtype: object

In [16]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2)
d = {
    'RandomForestClassifier': RandomForestClassifier(),
    'LogisticRegression': LogisticRegression(),
    'SVC': SVC(),
    'DecisionTreeClassifier': DecisionTreeClassifier(),
    'MLPClassifier': MLPClassifier()
}


def hh(model):
    classifier = model
    classifier.fit(x_train, y_train)
    y_pred = classifier.predict(x_test)
    return accuracy_score(y_test, y_pred)


for i, j in d.items():
    print(i, hh(j))

RandomForestClassifier 0.9940119760479041
LogisticRegression 0.9940119760479041
SVC 0.9940119760479041
DecisionTreeClassifier 0.9880239520958084
MLPClassifier 0.9940119760479041

AttributeError: 'Series' object has no attribute 'int'

In [17]:
from sklearn.linear_model import LinearRegression

In [19]:
from sklearn.linear_model import Lasso

In [20]:
from sklearn.linear_model import Ridge

In [21]:
ls=Lasso()

In [22]:
ls

Lasso()

In [ ]:
RandomForestClassifier()